### ISSUE TITLE
Refactor the code 

### ISSUE THREAD

**Issue by CedricMurairi** [alu-rwa-prog-1/final_project_part1-python_zen_cedric_mthabisi#5]
Keep one file for classes and the main file for the main program with all the user interactions.

**Comment by mtndlovu** [comment]
Have you started working on this? I want to start working on the UI. Can I safely make these changes on life.py?

**Comment by CedricMurairi** [comment]
Not yet started! I believe you can still work safely on life.py. No conflicts, fingers crossed!
