### ISSUE TITLE
Create text-based user interface

### ISSUE THREAD

**Issue by mtndlovu** [alu-rwa-prog-1/final_project_part1-python_zen_cedric_mthabisi#8]
**File Affected**: https://github.com/alu-rwa-prog-1/final_project_part1-python_zen_cedric_mthabisi/life/life.py

**What needs to be done?**

- Create a text-based user interface for users to play the Game of Life on the Python console. 

Users should be able to:
1. start the game, 
2. choose the initial state of the game by selecting which cells they want to be alive, 
3. or choose one of the boards with pre-built game states e.g. `GliderBoard`,
4. stop the game at any stage,
5. and restart the game

**Comment by CedricMurairi** [comment]
This is quite neat! Should we use coloring in the console? To tell which cell is dead or alive, or better, change colors when the board updates.

**Comment by mtndlovu** [comment]
Yes, I think it would be cool. But I think I'll not change much about how we display our board. My main focus is to have a crisp text-based user interface, then we can add many nice things to it as we see fit.
